### ISSUE TITLE
Question about PS2toAmiga

### ISSUE THREAD

**Issue by slappy32** [Jartza/PS2toAmiga#2]
Hello there,
your PS2 to Amiga looks interesting. Can you also make it work in the opposite direction, so that you can connect an 
Amiga keyboard to a PS/2 port?

I own an A1200 in a tower upgrade kit by Mikronik. Back in the 90's that company installed an internal PS/2 keyboard interface (= PS/2 port at the back of the tower.) The original A1200 keyboard went into an external chassis that contained an internal adapter to turn the A1200 into a PS/2 keyboard,  while the reset function "Ctrl + leftA + rightA" had been preserved. 
But that Mikronik keyboard interface is not the best one, translates only one key-press at a time. And the keys of my A1200 KB have gotten an ugly shade of yellow.
Now I would like to connect one of those nice, rare and black CDTV keyboards to the PS/2 port of my tower and need to convert the Amiga keyboard protocol accordingly. And I can only find some adapters online that convert Amiga keyboards to USB - but my PS/2 port won't understand USB-protocol jsut using one of those cheap USB-to-PS/2 plugs in green or violet.

Further questions:
1. If it is possible to make your adapter work from Amiga keyboard to PS/2 could you do so and offer me one
   ready to use for a good price?
  b) Or at least provide the PCB, that special IC chip flashed with your programm readily,  and provide some short step-by-step   
      soldering instructions?
      
Hope you can help a little.
Greetings,
slappy32

**Comment by Jartza** [comment]
Hi. Sorry for delay in answering, I had muted the issues-emails for some reason and only noticed this.

The answer to question is: unfortunately no, it's not easy nor feasible to use this for other-way communication. The PS2 keyboard -reader is using ready library (PS2KeyAdvanced) and the Amiga-side is write-only, implemented as bitbanging protocol. It would require full rewrite of the firmware, and I only wrote this for my own needs to connect a small PS2-keyboard to my Amiga CD32.
